---
title: "Template for lecture slides"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Template for lecture slides}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TeX distributions

A tex distribution has to be installed. For simplicity and compatibility you can install TeX Live through
the R package [tinytex](https://github.com/yihui/tinytex), available through CRAN or github.
When compiling the lecture slides template for the first time, a bunch of additional TeX packages have to
be installed. This can take several minutes. Be patient!

## Plotting with tikzDevice

The default plotting device is `tikz` provided by the package tikzDevice. It is possible that plotting fails due to missing tex packages,
that are required by tikzDevice (e.g. *grfext*). This can be tested using `tikzDevice::tikzTest()`. Watch out for errors like

```
! LaTeX Error: File `grfext.sty' not found.
```

and install missing packages using `tinytex::tlmgr_install("grfext")` or using the package manager shipped with your tex distribution.

## YAML parameters

| Command | Description |
| ------- | ----------- |
| `lang` | `character` Language of the presentation. One of "de" or "en". Defaults to "en".|
| `footerstyle` | `character` One of "default" or "colored". |
| `towers` | `logical` Should the title page include a gradient logo of the university buildings. |
| `template` | `character` The template to be used. Defaults to default |
| `colorlinks` | `logical` Should links be colored |
| `tables` | `logical` Should the latex packages "longtables" and "bookstabs" be included. |
| `institute` | `logical` or `character`. Should the name of the institution be included on the title page. Defaults to `TRUE` and includes the name of the University Duisburg-Essen in the language specified by lang. If a character object is provided, this string is shown underneath the title. |
| `blockstyle` | `character` The style of the beamer block environments (theorems, examples, etc.). One of "box" or "blank". Defaults to "box". |
| `shadecolor` | `numeric` The shade of grey used as the background color for code chunks. A number between 0 and 1. |
| `logo` | `character` Path to a logo for the slides. If not set otherwise, a UDE logo is used. |
| `incremental` | `logical` Should the slides render incrementally. Defaults to `FALSE`. |
| `fig_width` | `numeric` Default width of figures in inches. Defaults to 10. |
| `fig_height` | `numeric` Default height of figures in inches. Defaults to 7. |
| `fig_crop` | `logical` Should white space be cropped from figures. |
| `fig_caption` | `logical` Should figure captions be used. Defaults to `TRUE`. |
| `dev` | `character` The graphic device to be used. Defaults to "tikz". |
| `df_print` | See \link[rmarkdown]{output_format}. |
| `theme` | `character` The theme for the slides. |
| `colortheme` | `character` The color theme for the slides.|
| `fonttheme` | `character` The font theme for the slides. |
| `highlight` | `character` One of `rmarkdown:::highlighters()`. |
| `slidelevel` | `numeric` Depth of slide numbering. Defaults to 2. |

## Additional Latex commands

| Command | Description | Example |
| ------- | ----------- | ------- |
| `\source{}` | Easily add the source for a figure, table or another element. | `\source{R Core Team (2013)}` |
| `\npt` | Insert a linebreak and pause (`\\[1ex]\pause`)| `\npt` |
| `\nbs` | Insert a non-breaking space. | `\nbs` |
| `\qedb` | `\qed` in blue. | `\qedb` |
| `\hil` | Highlight text in blue and bold font. | `\hil{important information}` |
| `\hilm` | Highlight math in blue and bold (if available) font.| `\hilm{\alpha\beta\gamma}` |
| `\mps` | Insert a medium paragraph break (`\par\medbreak`)| `\mps`|
| `\EE` |}[1]{\E\left(#1\right)}
| `\Pr` |}{\ensuremath{\mathrm{P}}}
| `\Prob` |}[1]{\Pr\left(#1\right)}
| `\Spur` |}[1]{\spur\left[#1\right]}
| `\vvarphi` |}{\bm \varphi}
| `\GEV` | Short for `\operatorname{GEV}` |`\GEV`|
| `\GP` | Short for `\operatorname{GP}` |`\GP`|
| `\SE` | Short for `\operatorname{SE}` |`\SE`|
| `\AIC` | Short for `\operatorname{AIC}` |`\AIC`|
| `\BIC` | Short for `\operatorname{BIC}` |`\BIC`|
| `\SBC` | Short for `\operatorname{SBC}` | `\SBC` |
| `\bmtheta` | Short for `\boldmath\theta` | `\bmtheta` |
| `\di` | Short for `\mathrm{i}` | `\di` |
